/**
 * Created by qinchuan on 2017/10/1.
 */
export const TESTACTION='TESTACTION';

export const HOMEACTION={
    GET_EVERYDAY_IMG:'GET_EVERYDAY_IMG'
}

export const ROOTACTION={
    SET_GLOBAL_CONFIG:'SET_GLOBAL_CONFIG'
}

export const OURACTION={
    SET_MUSIC_STATE:'SET_MUSIC_STATE',
    SET_MUSIC_CONFIG:'SET_MUSIC_CONFIG'
}

export const EMOTIONACTION={
    GET_WEATHER_INFO:'GET_WEATHER_INFO',
    GET_AIR_INFO:'GET_AIR_INFO',
    GET_ALL_WEATHER_INFO:'GET_ALL_WEATHER_INFO'
}